package gui;

import formula.PilotoLibre;
import java.util.Iterator;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME3
 */
public class FrameEscuderia extends javax.swing.JFrame {

    /**
     * Creates new form FrameEscuderia
     */
    public FrameEscuderia() {
        initComponents();
        jLPConfigurarCarrera.setVisible(false);
        jLPDescartarPiloto.setVisible(false);
        jLPEntrenamiento.setVisible(false);
        jLPFabricarCoche.setVisible(false);
        jLPFicharPiloto.setVisible(false);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPDescartarPiloto = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTDescartarPilotosOficiales1 = new javax.swing.JTable();
        jBDespedirPiloto = new javax.swing.JButton();
        jLPEntrenamiento = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxEscuderia = new javax.swing.JComboBox();
        jComboBoxEscuderia1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxEscuderiaCoches = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTFicharPilotosOficiales1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLPFicharPiloto = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jBContratar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFicharPilotosOficiales = new javax.swing.JTable();
        jLPConfigurarCarrera = new javax.swing.JLayeredPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jComboBox14 = new javax.swing.JComboBox();
        jComboBox15 = new javax.swing.JComboBox();
        jComboBox16 = new javax.swing.JComboBox();
        jComboBox17 = new javax.swing.JComboBox();
        jComboBox18 = new javax.swing.JComboBox();
        jComboBox19 = new javax.swing.JComboBox();
        jComboBox20 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLPFabricarCoche = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEscuderia2 = new javax.swing.JComboBox();
        jSlider1 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSlider4 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLPEscuderiaPrincipal = new javax.swing.JLayeredPane();
        jLGestionDeEscuderia = new javax.swing.JLabel();
        jBEntrenamiento = new javax.swing.JButton();
        jBFicharPiloto = new javax.swing.JButton();
        jBDescartarPiloto = new javax.swing.JButton();
        jBConfigurarCarrera = new javax.swing.JButton();
        jBtnEscuderiaVolver = new javax.swing.JButton();
        jBFabricarCoche = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(231, 230, 233));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jLabel5.setText("DESCARTAR PILOTO");

        jTDescartarPilotosOficiales1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Altura", "Peso", "Reflejos", "Agresividad", "Paciencia", "Valentia", "Valoración Global", "Sueldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTDescartarPilotosOficiales1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTDescartarPilotosOficiales1InputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jTDescartarPilotosOficiales1);

        jBDespedirPiloto.setForeground(new java.awt.Color(204, 51, 0));
        jBDespedirPiloto.setText("Descartar Piloto");
        jBDespedirPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDespedirPilotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLPDescartarPilotoLayout = new javax.swing.GroupLayout(jLPDescartarPiloto);
        jLPDescartarPiloto.setLayout(jLPDescartarPilotoLayout);
        jLPDescartarPilotoLayout.setHorizontalGroup(
            jLPDescartarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPDescartarPilotoLayout.createSequentialGroup()
                .addGroup(jLPDescartarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLPDescartarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBDespedirPiloto)
                        .addGroup(jLPDescartarPilotoLayout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(jLabel5)
                            .addGap(277, 277, 277)))
                    .addGroup(jLPDescartarPilotoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jLPDescartarPilotoLayout.setVerticalGroup(
            jLPDescartarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPDescartarPilotoLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBDespedirPiloto)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jLPDescartarPiloto.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPDescartarPiloto.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPDescartarPiloto.setLayer(jBDespedirPiloto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLPDescartarPiloto);

        jLabel2.setText("ENTRENAMIENTO");

        jLabel6.setText("Selecciona Circuito:");

        jComboBoxEscuderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEscuderiaActionPerformed(evt);
            }
        });

        jComboBoxEscuderia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEscuderia1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Selecciona Piloto:");

        jLabel8.setText("Selecciona Coche:");

        jComboBoxEscuderiaCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEscuderiaCochesActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Aforo", "Canon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Modelo", "Potencia", "Aerodinámica", "Neumáticos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jTFicharPilotosOficiales1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Altura", "Peso", "Valoración Global", "Reflejos", "Agresividad", "Paciencia", "Valentia", "Sueldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTFicharPilotosOficiales1.setColumnSelectionAllowed(true);
        jTFicharPilotosOficiales1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTFicharPilotosOficiales1InputMethodTextChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jTFicharPilotosOficiales1);
        jTFicharPilotosOficiales1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton2.setForeground(new java.awt.Color(51, 153, 0));
        jButton2.setText("Aceptar");

        javax.swing.GroupLayout jLPEntrenamientoLayout = new javax.swing.GroupLayout(jLPEntrenamiento);
        jLPEntrenamiento.setLayout(jLPEntrenamientoLayout);
        jLPEntrenamientoLayout.setHorizontalGroup(
            jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPEntrenamientoLayout.createSequentialGroup()
                .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLPEntrenamientoLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jLPEntrenamientoLayout.createSequentialGroup()
                                        .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLPEntrenamientoLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(27, 27, 27)
                                                .addComponent(jComboBoxEscuderiaCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLPEntrenamientoLayout.createSequentialGroup()
                                                .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6))
                                                .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jLPEntrenamientoLayout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addComponent(jComboBoxEscuderia1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jLPEntrenamientoLayout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jComboBoxEscuderia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(386, 386, 386))
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jLPEntrenamientoLayout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jLPEntrenamientoLayout.setVerticalGroup(
            jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPEntrenamientoLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEscuderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEscuderia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEscuderiaCoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPEntrenamiento.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jComboBoxEscuderia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jComboBoxEscuderia1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jComboBoxEscuderiaCoches, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEntrenamiento.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLPEntrenamiento);

        jLabel4.setText("FICHAR PILOTO");

        jBContratar.setForeground(new java.awt.Color(0, 204, 0));
        jBContratar.setText("Contratar");
        jBContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContratarActionPerformed(evt);
            }
        });

        jTFicharPilotosOficiales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Altura", "Peso", "Reflejos", "Agresividad", "Paciencia", "Valentia", "Valoración Global", "Sueldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTFicharPilotosOficiales.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTFicharPilotosOficialesInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTFicharPilotosOficiales);

        javax.swing.GroupLayout jLPFicharPilotoLayout = new javax.swing.GroupLayout(jLPFicharPiloto);
        jLPFicharPiloto.setLayout(jLPFicharPilotoLayout);
        jLPFicharPilotoLayout.setHorizontalGroup(
            jLPFicharPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPFicharPilotoLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel4)
                .addContainerGap(478, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPFicharPilotoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBContratar)
                .addGap(24, 24, 24))
            .addGroup(jLPFicharPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPFicharPilotoLayout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        jLPFicharPilotoLayout.setVerticalGroup(
            jLPFicharPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPFicharPilotoLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(jBContratar)
                .addGap(41, 41, 41))
            .addGroup(jLPFicharPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPFicharPilotoLayout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );
        jLPFicharPiloto.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFicharPiloto.setLayer(jBContratar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFicharPiloto.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLPFicharPiloto);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Aforo", "Canon", "Distancia Rectas", "Distancia Curvas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Piloto 1");

        jLabel15.setText("Piloto 2");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("CARRERA 1");

        jLabel16.setText("CARRERA 2");

        jLabel17.setText("CARRERA 3");

        jLabel18.setText("CARRERA 4");

        jLabel19.setText("CARRERA 5");

        jLabel20.setText("Coche 1");

        jLabel21.setText("Coche 2");

        jButton6.setForeground(new java.awt.Color(0, 153, 0));
        jButton6.setText("Aceptar");

        jLabel22.setText("CONFIGURAR CARRERAS");

        javax.swing.GroupLayout jLPConfigurarCarreraLayout = new javax.swing.GroupLayout(jLPConfigurarCarrera);
        jLPConfigurarCarrera.setLayout(jLPConfigurarCarreraLayout);
        jLPConfigurarCarreraLayout.setHorizontalGroup(
            jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPConfigurarCarreraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(236, 236, 236))
            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(39, 39, 39)
                        .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                                .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                                .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))
                    .addComponent(jSeparator5))
                .addGap(0, 194, Short.MAX_VALUE))
        );
        jLPConfigurarCarreraLayout.setVerticalGroup(
            jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPConfigurarCarreraLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel22)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(11, 11, 11)
                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(27, 27, 27)
                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(28, 28, 28)
                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(27, 27, 27)
                .addGroup(jLPConfigurarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jLPConfigurarCarrera.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jComboBox20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPConfigurarCarrera.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLPConfigurarCarrera);

        jLabel3.setText("FABRICAR COCHE");

        jLabel9.setText("Selecciona Modelo:");

        jComboBoxEscuderia2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Modelos", "Ferrari", "Renault", "McLaren", "Mercedes", "Lotus", "Red Bull", "Force India", "Sauber", "Toro Rosso", "Williams", "Marussia", "Caterham" }));
        jComboBoxEscuderia2.setName(""); // NOI18N
        jComboBoxEscuderia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEscuderia2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Potencia:");

        jLabel12.setText("Aerodinámica:");

        jLabel13.setText("Neumáticos:");

        jButton5.setText("Restablecer");

        jButton4.setForeground(new java.awt.Color(51, 153, 0));
        jButton4.setText("Aceptar");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jLPFabricarCocheLayout = new javax.swing.GroupLayout(jLPFabricarCoche);
        jLPFabricarCoche.setLayout(jLPFabricarCocheLayout);
        jLPFabricarCocheLayout.setHorizontalGroup(
            jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPFabricarCocheLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLPFabricarCocheLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSlider4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(225, Short.MAX_VALUE))
                    .addGroup(jLPFabricarCocheLayout.createSequentialGroup()
                        .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLPFabricarCocheLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxEscuderia2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPFabricarCocheLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jLPFabricarCocheLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPFabricarCocheLayout.setVerticalGroup(
            jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPFabricarCocheLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEscuderia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSlider4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSlider3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jLPFabricarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jLPFabricarCoche.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jComboBoxEscuderia2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jSlider1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jSlider3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jSlider4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFabricarCoche.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLPFabricarCoche);

        jLPEscuderiaPrincipal.setBackground(new java.awt.Color(51, 153, 255));
        jLPEscuderiaPrincipal.setToolTipText("");

        jLGestionDeEscuderia.setText("GESTIÓN DE ESCUDERÍA");

        jBEntrenamiento.setText("Entrenamiento");
        jBEntrenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrenamientoActionPerformed(evt);
            }
        });

        jBFicharPiloto.setText("Fichar Piloto");
        jBFicharPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFicharPilotoActionPerformed(evt);
            }
        });

        jBDescartarPiloto.setText("Descartar Piloto");
        jBDescartarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescartarPilotoActionPerformed(evt);
            }
        });

        jBConfigurarCarrera.setText("Configurar Carrera");
        jBConfigurarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfigurarCarreraActionPerformed(evt);
            }
        });

        jBtnEscuderiaVolver.setForeground(new java.awt.Color(204, 0, 0));
        jBtnEscuderiaVolver.setText("Volver");
        jBtnEscuderiaVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEscuderiaVolverActionPerformed(evt);
            }
        });

        jBFabricarCoche.setText("Fabricar Coche");
        jBFabricarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFabricarCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLPEscuderiaPrincipalLayout = new javax.swing.GroupLayout(jLPEscuderiaPrincipal);
        jLPEscuderiaPrincipal.setLayout(jLPEscuderiaPrincipalLayout);
        jLPEscuderiaPrincipalLayout.setHorizontalGroup(
            jLPEscuderiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPEscuderiaPrincipalLayout.createSequentialGroup()
                .addGroup(jLPEscuderiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLPEscuderiaPrincipalLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLGestionDeEscuderia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnEscuderiaVolver))
                    .addGroup(jLPEscuderiaPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBFicharPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBDescartarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBConfigurarCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(jBEntrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBFabricarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jLPEscuderiaPrincipalLayout.setVerticalGroup(
            jLPEscuderiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPEscuderiaPrincipalLayout.createSequentialGroup()
                .addGroup(jLPEscuderiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGestionDeEscuderia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEscuderiaVolver))
                .addGap(18, 18, 18)
                .addGroup(jLPEscuderiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConfigurarCarrera)
                    .addComponent(jBFicharPiloto)
                    .addComponent(jBFabricarCoche)
                    .addComponent(jBEntrenamiento)
                    .addComponent(jBDescartarPiloto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPEscuderiaPrincipal.setLayer(jLGestionDeEscuderia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEscuderiaPrincipal.setLayer(jBEntrenamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEscuderiaPrincipal.setLayer(jBFicharPiloto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEscuderiaPrincipal.setLayer(jBDescartarPiloto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEscuderiaPrincipal.setLayer(jBConfigurarCarrera, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEscuderiaPrincipal.setLayer(jBtnEscuderiaVolver, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEscuderiaPrincipal.setLayer(jBFabricarCoche, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEscuderiaPrincipal.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLPEscuderiaPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void jBtnEscuderiaVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEscuderiaVolverActionPerformed
        FrameManager.getInstance().mostrarVentanaPrincipal(this);
    }//GEN-LAST:event_jBtnEscuderiaVolverActionPerformed

    private void jComboBoxEscuderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEscuderiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEscuderiaActionPerformed

    private void jTFicharPilotosOficialesInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTFicharPilotosOficialesInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFicharPilotosOficialesInputMethodTextChanged

    private void jTDescartarPilotosOficiales1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTDescartarPilotosOficiales1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDescartarPilotosOficiales1InputMethodTextChanged

    private void jComboBoxEscuderia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEscuderia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEscuderia1ActionPerformed

    private void jComboBoxEscuderiaCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEscuderiaCochesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEscuderiaCochesActionPerformed

    private void jTFicharPilotosOficiales1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTFicharPilotosOficiales1InputMethodTextChanged

    }//GEN-LAST:event_jTFicharPilotosOficiales1InputMethodTextChanged

    private void jComboBoxEscuderia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEscuderia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEscuderia2ActionPerformed

    private void jBConfigurarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfigurarCarreraActionPerformed
        this.jLPConfigurarCarrera.setVisible(true);
        this.jLPDescartarPiloto.setVisible(false);
        this.jLPEntrenamiento.setVisible(false);
        this.jLPFabricarCoche.setVisible(false);
        this.jLPFicharPiloto.setVisible(false);
    }//GEN-LAST:event_jBConfigurarCarreraActionPerformed

    private void jBFabricarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFabricarCocheActionPerformed
        this.jLPConfigurarCarrera.setVisible(false);
        this.jLPDescartarPiloto.setVisible(false);
        this.jLPEntrenamiento.setVisible(false);
        this.jLPFabricarCoche.setVisible(true);
        this.jLPFicharPiloto.setVisible(false);
    }//GEN-LAST:event_jBFabricarCocheActionPerformed

    private void jBEntrenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrenamientoActionPerformed
        this.jLPConfigurarCarrera.setVisible(false);
        this.jLPDescartarPiloto.setVisible(false);
        this.jLPEntrenamiento.setVisible(true);
        this.jLPFabricarCoche.setVisible(false);
        this.jLPFicharPiloto.setVisible(false);
    }//GEN-LAST:event_jBEntrenamientoActionPerformed

    private void jBFicharPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFicharPilotoActionPerformed
        this.jLPConfigurarCarrera.setVisible(false);
        this.jLPDescartarPiloto.setVisible(false);
        this.jLPEntrenamiento.setVisible(false);
        this.jLPFabricarCoche.setVisible(false);
        this.jLPFicharPiloto.setVisible(true);
    }//GEN-LAST:event_jBFicharPilotoActionPerformed

    private void jBDescartarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescartarPilotoActionPerformed
        this.jLPConfigurarCarrera.setVisible(false);
        this.jLPDescartarPiloto.setVisible(true);
        this.jLPEntrenamiento.setVisible(false);
        this.jLPFabricarCoche.setVisible(false);
        this.jLPFicharPiloto.setVisible(false);
    }//GEN-LAST:event_jBDescartarPilotoActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
                // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jBDespedirPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDespedirPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDespedirPilotoActionPerformed

    private void jBContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContratarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBContratarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEscuderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEscuderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEscuderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEscuderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEscuderia().setVisible(true);
            }
        });
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfigurarCarrera;
    private javax.swing.JButton jBContratar;
    private javax.swing.JButton jBDescartarPiloto;
    private javax.swing.JButton jBDespedirPiloto;
    private javax.swing.JButton jBEntrenamiento;
    private javax.swing.JButton jBFabricarCoche;
    private javax.swing.JButton jBFicharPiloto;
    private javax.swing.JButton jBtnEscuderiaVolver;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox17;
    private javax.swing.JComboBox jComboBox18;
    private javax.swing.JComboBox jComboBox19;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox20;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JComboBox jComboBoxEscuderia;
    private javax.swing.JComboBox jComboBoxEscuderia1;
    private javax.swing.JComboBox jComboBoxEscuderia2;
    private javax.swing.JComboBox jComboBoxEscuderiaCoches;
    private javax.swing.JLabel jLGestionDeEscuderia;
    private javax.swing.JLayeredPane jLPConfigurarCarrera;
    private javax.swing.JLayeredPane jLPDescartarPiloto;
    private javax.swing.JLayeredPane jLPEntrenamiento;
    private javax.swing.JLayeredPane jLPEscuderiaPrincipal;
    private javax.swing.JLayeredPane jLPFabricarCoche;
    private javax.swing.JLayeredPane jLPFicharPiloto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JTable jTDescartarPilotosOficiales1;
    private javax.swing.JTable jTFicharPilotosOficiales;
    private javax.swing.JTable jTFicharPilotosOficiales1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
